CREATE TABLE accounts (
    id bigserial primary key,
    created_at timestamp default now() not null, /*should be autogenerated on insert, we may want created and updated on all tables in the future */
    username varchar(64) not null,
    display_name varchar(64) not null,
    guest_account boolean not null,
    constraint username_unique unique (username)
);

CREATE TABLE account_passwords (
    account_id bigint not null,
    password_hash bytea not null,
    password_salt bytea not null,
    foreign key (account_id) references accounts(id),
    constraint unique_account_id unique (account_id)
);

CREATE TABLE roles (
    role varchar(16) primary key,
    constraint unique_role unique (role)
);

INSERT INTO roles(role) values ('admin'), ('user'), ('guest');

CREATE TABLE account_roles (
    account_id bigint not null,
    role varchar(16) not null,
    primary key (account_id, role),
    foreign key (account_id) references accounts(id),
    foreign key (role) references roles(role)
);

CREATE TABLE account_profiles (
    account_id bigint not null,
    first_name varchar(50),
    last_name varchar(50),
    email varchar(128),
    phone varchar(20),
    foreign key (account_id) references accounts(id),
    constraint one_profile_per_account unique (account_id)
);